version: '3.8'
services:
  ackService:
    build: .
    container_name: ackService
    hostname: ackService
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: unless-stopped
    depends_on: 
      - mongodb
  ackDatabase:
    image: postgres:latest
    container_name: ackDatabase
    hostname: ackDatabase
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ack
      PGDATA: /data/postgres
    volumes:
      - dbdata:/data/postgres
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata: